.TH "Répertoire de référence de UNO/test" 3 "Mercredi 13 Mai 2020" "Version 1.4" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de UNO/test
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBcsvloader_test\&.c\fP"
.br
.ti -1c
.RI "fichier \fBpile_test\&.c\fP"
.br
.ti -1c
.RI "fichier \fBplay_test\&.c\fP"
.br
.in -1c
