.TH "Répertoire de référence de UNO/include" 3 "Jeudi 30 Avril 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de UNO/include
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBcarte\&.h\fP"
.br
.ti -1c
.RI "fichier \fBcsvloader\&.h\fP"
.br
.ti -1c
.RI "fichier \fBjoueur\&.h\fP"
.br
.ti -1c
.RI "fichier \fBpile\&.h\fP"
.br
.ti -1c
.RI "fichier \fBplay\&.h\fP"
.br
.in -1c
