.TH "card" 3 "Samedi 2 Mai 2020" "Version 1.3" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
card
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <carte\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBnum\fP"
.br
.RI "Indice du symbole\&. "
.ti -1c
.RI "char \fBcolor\fP"
.br
.RI "Couleur de la carte\&. "
.ti -1c
.RI "char * \fBsymbol\fP"
.br
.RI "Symbole\&. "
.in -1c
.SH "Description détaillée"
.PP 
Structure d'une carte Une carte contient un numero, une couleur et un symbole\&. 
.PP
Définition à la ligne 8 du fichier carte\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "char color"

.PP
Couleur de la carte\&. 
.PP
Définition à la ligne 13 du fichier carte\&.h\&.
.SS "char num"

.PP
Indice du symbole\&. 
.PP
Définition à la ligne 11 du fichier carte\&.h\&.
.SS "char* symbol"

.PP
Symbole\&. 
.PP
Définition à la ligne 15 du fichier carte\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
