.TH "UNO/carte.c" 3 "Samedi 2 Mai 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/carte.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'include/carte\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBcard_t\fP * \fBcard_Init\fP (char num, char color)"
.br
.RI "Initialise une carte\&. "
.ti -1c
.RI "void \fBcard_Display\fP (\fBcard_t\fP *c)"
.br
.RI "Afficche une carte\&. "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void card_Display (\fBcard_t\fP * carte)"

.PP
Afficche une carte\&. Affiche une carte 
.PP
\fBParamètres\fP
.RS 4
\fIcarte\fP la carte à afficher 
.RE
.PP

.SS "\fBcard_t\fP* card_Init (char num, char couleur)"

.PP
Initialise une carte\&. Initialise une Carte 
.PP
\fBParamètres\fP
.RS 4
\fInum\fP symbol de la carte 
.br
\fIcouleur\fP couleur de la carte 
.RE
.PP
\fBRenvoie\fP
.RS 4
la carte creer 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
