.TH "csv" 3 "Samedi 2 Mai 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csv
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csvloader\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "\fBdata_t\fP * \fBdata\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'un fichier csv\&. Il s'agit simplement d'un vecteur de donnée et avec le nombre d'éléments\&. 
.SH "Documentation des champs"
.PP 
.SS "\fBdata_t\fP* \fBdata\fP"

.SS "int length"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
