.TH "UNO/src/csvloader.c" 3 "Mercredi 13 Mai 2020" "Version 1.4" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/src/csvloader.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'csvloader\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBcsv_t\fP * \fBcsv_InitCSV\fP (FILE *f)"
.br
.RI "Charge un fichier csv\&. "
.ti -1c
.RI "void \fBcsv_DeleteCSV\fP (\fBcsv_t\fP *\fBcsv\fP)"
.br
.RI "Libere la memoire\&. "
.ti -1c
.RI "\fBcsv_t\fP * \fBcsv_ParseCSV\fP (const \fBstring_t\fP filename, \fBcsv_t\fP *input)"
.br
.RI "Sépare les données du ficher et les stocke dans un objet\&. "
.ti -1c
.RI "void \fBcsv_PrintData\fP (\fBdata_t\fP *d)"
.br
.RI "Affiche le contenue d'une donnée (ligne d'un fichier csv) "
.ti -1c
.RI "void \fBcsv_PrintCSV\fP (\fBcsv_t\fP *\fBcsv\fP, \fBdataPrinter\fP printer)"
.br
.RI "Affiche les donnée stocker dans l'objet\&. "
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void csv_DeleteCSV (\fBcsv_t\fP * csv)"

.PP
Libere la memoire\&. Libere la memoire d'un objet csv\&. 
.PP
\fBParamètres\fP
.RS 4
\fIcsv\fP l'objet a supprimer\&. 
.RE
.PP

.PP
Définition à la ligne 27 du fichier csvloader\&.c\&.
.SS "\fBcsv_t\fP* csv_InitCSV (FILE * f)"

.PP
Charge un fichier csv\&. Initialise un objet CSV a partire d'un fichier\&. 
.PP
\fBParamètres\fP
.RS 4
\fIf\fP le a charger\&. 
.RE
.PP

.PP
Définition à la ligne 10 du fichier csvloader\&.c\&.
.SS "\fBcsv_t\fP* csv_ParseCSV (\fBstring_t\fP filename, \fBcsv_t\fP * input)"

.PP
Sépare les données du ficher et les stocke dans un objet\&. Traite les données du fichier csv et les stocke dans la structure\&. 
.PP
\fBParamètres\fP
.RS 4
\fIfilename\fP nom du fichier\&. 
.br
\fIinput\fP object concerner\&. 
.RE
.PP
\fBRenvoie\fP
.RS 4
l'objet creer si input est null, sinon input\&. 
.RE
.PP

.PP
Définition à la ligne 39 du fichier csvloader\&.c\&.
.SS "void csv_PrintCSV (\fBcsv_t\fP * csv, \fBdataPrinter\fP printer)"

.PP
Affiche les donnée stocker dans l'objet\&. Affiche le contenu d'un fichier CSV\&. 
.PP
\fBParamètres\fP
.RS 4
\fIcsv\fP l'objet dans le quel sont stocker les données\&. 
.br
\fIprinter\fP fonction d'affichage des données\&. 
.RE
.PP

.PP
Définition à la ligne 81 du fichier csvloader\&.c\&.
.SS "void csv_PrintData (\fBdata_t\fP * d)"

.PP
Affiche le contenue d'une donnée (ligne d'un fichier csv) Affiche une ligne de donnée d'un fichier csv\&. 
.PP
\fBParamètres\fP
.RS 4
\fId\fP la ligne de donnée\&. 
.RE
.PP

.PP
Définition à la ligne 72 du fichier csvloader\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
