.TH "data" 3 "Lundi 27 Avril 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csvloader\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "char \fBmessage\fP [\fB__CSV_BUFFER_SIZE__\fP]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'une lingne de donnée d'un fichier csv\&. Ici l'index est n'utilisé Le message correspond à l'affichage durant la partie\&. 
.SH "Documentation des champs"
.PP 
.SS "int index"

.SS "char message[\fB__CSV_BUFFER_SIZE__\fP]"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
