.TH "UNO/joueur.c" 3 "Mardi 5 Mai 2020" "Version 1.3" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/joueur.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'include/pile\&.h'\fP
.br
\fC#include 'include/joueur\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNombre_carte\fP   7"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBplayer_t\fP * \fBplayer_Init\fP (int nb, char *noms[], \fBpile_t\fP *deck)"
.br
.RI "Initialise les joueurs\&. "
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define Nombre_carte   7"

.PP
Définition à la ligne 7 du fichier joueur\&.c\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBplayer_t\fP* player_Init (int nb, char * noms[], \fBpile_t\fP * deck)"

.PP
Initialise les joueurs\&. 
.PP
Définition à la ligne 9 du fichier joueur\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
