.TH "UNO/src/main.c" 3 "Mercredi 13 Mai 2020" "Version 1.4" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'carte\&.h'\fP
.br
\fC#include 'pile\&.h'\fP
.br
\fC#include 'joueur\&.h'\fP
.br
\fC#include 'play\&.h'\fP
.br
\fC#include 'csvloader\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmaxPoint\fP   500"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBg_Reset\fP (\fBpile_t\fP *pioche, \fBplayer_t\fP *joueurs, int nb)"
.br
.RI "Réinitialise les cartes des joueurs et distribue de nouvelle cartes aux joueurs\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define maxPoint   500"

.PP
Définition à la ligne 13 du fichier main\&.c\&.
.SH "Documentation des fonctions"
.PP 
.SS "void g_Reset (\fBpile_t\fP * pioche, \fBplayer_t\fP * joueurs, int nb)"

.PP
Réinitialise les cartes des joueurs et distribue de nouvelle cartes aux joueurs\&. 
.PP
Définition à la ligne 15 du fichier main\&.c\&.
.SS "int main (int argc, char ** argv)"

.PP
Définition à la ligne 26 du fichier main\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
