.TH "md__c_1_dev__c__real_programme__u_n_o__r_e_a_d_m_e" 3 "Lundi 27 Avril 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_dev__c__real_programme__u_n_o__r_e_a_d_m_e \- UNO 

.SH "Combien de cartes dans le Uno ? Pour jouer au Uno, il vous faut les 108 cartes réparties de cette manière :"
.PP
.IP "\(bu" 2
19 cartes de couleur bleu, numérotées de 0 à 9 (\fI2 pour chaque chiffre sauf pour le 0\fP)
.IP "\(bu" 2
19 cartes de couleur rouge, numérotées de 0 à 9 (\fI2 pour chaque chiffre sauf pour le 0\fP)
.IP "\(bu" 2
19 cartes de couleur jaune, numérotées de 0 à 9 (\fI2 pour chaque chiffre sauf pour le 0\fP)
.IP "\(bu" 2
19 cartes de couleur verte, numérotées de 0 à 9 (\fI2 pour chaque chiffre sauf pour le 0\fP)
.PP
.SH "et des cartes spéciales:"
.PP
.IP "\(bu" 2
8 cartes « \fB+2\fP », (\fI2 pour chaque couleur\fP)
.IP "\(bu" 2
8 cartes « \fBInversement de sens\fP », (\fI2 pour chaque couleur\fP)
.IP "\(bu" 2
8 cartes « \fBPasse ton tour\fP », (\fI2 pour chaque couleur\fP)
.IP "\(bu" 2
4 cartes « \fBJoker\fP »
.IP "\(bu" 2
4 cartes « \fB+4\fP »
.PP
.SH "Le pouvoir des cartes spéciales Uno :"
.PP
\fBLa carte « \fI+2\fP » :\fP Lorsqu’un joueur joue cette carte, le joueur suivant doit piocher 2 cartes et passe son tour et cela même si c’est la première carte retournée en début de partie\&.
.PP
\fBLa carte « \fIInversement de sens\fP » :\fP
.PP
Lorsqu’un joueur joue cette carte, le sens de la partie est inversée\&. Si la partie se déroulait dans le sens des aiguilles d’une montre, elle passera donc dans le sens inverse\&. Même si elle est la première carte retournée en début de partie, elle doit être prise en compte\&.
.PP
\fBLa carte « \fIPasse ton tour\fP » :\fP
.PP
Lorsqu’un joueur joue cette carte, le joueur suivant doit passer son tour\&. Même si elle est la première carte retournée en début de partie, elle doit être prise en compte\&.
.PP
\fCsources\fP 
