.TH "pile" 3 "Mardi 5 Mai 2020" "Version 1.3" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pile\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fB_TOP\fP"
.br
.ti -1c
.RI "\fBcard_t\fP * \fB_DATA\fP [\fBPILE_MAX\fP]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure de pile Contient l'indice du sommet du paquet\&. Un vecteur de carte_t\&. Il sagit d'un paquet de carte utilisé comme pioche et main des joueurs\&. 
.PP
Définition à la ligne 12 du fichier pile\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "\fBcard_t\fP* _DATA[\fBPILE_MAX\fP]"

.PP
Définition à la ligne 15 du fichier pile\&.h\&.
.SS "int _TOP"

.PP
Définition à la ligne 14 du fichier pile\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
