.TH "UNO/test/pile_test.c" 3 "Mercredi 13 Mai 2020" "Version 1.4" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/test/pile_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'carte\&.h'\fP
.br
\fC#include 'pile\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBcard_Copy\fP (\fBcard_t\fP *dest, \fBcard_t\fP *src)"
.br
.RI "Copie une carte\&. "
.ti -1c
.RI "int \fBcard_Comp\fP (\fBcard_t\fP *cardA, \fBcard_t\fP *cardB)"
.br
.RI "Compare deux cartes\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int card_Comp (\fBcard_t\fP * cardA, \fBcard_t\fP * cardB)"

.PP
Compare deux cartes\&. 
.PP
Définition à la ligne 18 du fichier pile_test\&.c\&.
.SS "void card_Copy (\fBcard_t\fP * dest, \fBcard_t\fP * src)"

.PP
Copie une carte\&. 
.PP
Définition à la ligne 8 du fichier pile_test\&.c\&.
.SS "int main ()"

.PP
Définition à la ligne 27 du fichier pile_test\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
