.TH "player" 3 "Mercredi 13 Mai 2020" "Version 1.4" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <joueur\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBpile_t\fP * \fBcards\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'un joueur Elle contient le score le nom et les cartes d'un joueur\&. 
.PP
Définition à la ligne 9 du fichier joueur\&.h\&.
.SH "Documentation des champs"
.PP 
.SS "\fBpile_t\fP* cards"

.PP
Définition à la ligne 13 du fichier joueur\&.h\&.
.SS "char* name"

.PP
Définition à la ligne 12 du fichier joueur\&.h\&.
.SS "int score"

.PP
Définition à la ligne 11 du fichier joueur\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
