.TH "player" 3 "Jeudi 30 Avril 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <joueur\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBpile_t\fP * \fBcards\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'un joueur Elle contient le score le nom et les cartes d'un joueur\&. 
.SH "Documentation des champs"
.PP 
.SS "\fBpile_t\fP* cards"

.SS "char* name"

.SS "int score"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
