.TH "UNO/include/play.h" 3 "Lundi 27 Avril 2020" "Version 1.2" "UNO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNO/include/play.h
.SH SYNOPSIS
.br
.PP
\fC#include 'carte\&.h'\fP
.br
\fC#include 'pile\&.h'\fP
.br
\fC#include 'joueur\&.h'\fP
.br
\fC#include 'csvloader\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__PLAY_H__\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBnext\fP ()"
.br
.RI "Passe au tour suivant\&. "
.ti -1c
.RI "void \fBinverse\fP ()"
.br
.RI "Change de sens\&. "
.ti -1c
.RI "int \fBgetTour\fP ()"
.br
.RI "Renvoie la valeur des tours jouer\&. "
.ti -1c
.RI "void \fBsetTour\fP (int n)"
.br
.RI "Modifie la valeur de tour\&. "
.ti -1c
.RI "int \fBcan_play_cart\fP (\fBcard_t\fP *carte_A, \fBcard_t\fP *carte_B)"
.br
.ti -1c
.RI "int \fBcan_play\fP (\fBpile_t\fP *\fBmain\fP, \fBcard_t\fP *carte)"
.br
.RI "Verifie si un joueur peut jouer\&. "
.ti -1c
.RI "int \fBplay\fP (\fBplayer_t\fP *joueurs, \fBpile_t\fP *paquets, \fBpile_t\fP *pioches, int numt, int nbj, \fBcsv_t\fP *\fBcsv\fP)"
.br
.RI "Boucle principale du jeu\&. "
.ti -1c
.RI "int \fBask\fP (int *v, char *message, char *message2)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define __PLAY_H__"

.SH "Documentation des fonctions"
.PP 
.SS "int ask (int * v, char * message, char * message2)"

.SS "int can_play (\fBpile_t\fP * main, \fBcard_t\fP * carte)"

.PP
Verifie si un joueur peut jouer\&. Vérifie si un joueur possède une carte jouable\&. 
.PP
\fBParamètres\fP
.RS 4
\fImain\fP pile des carte d'un joueur\&. 
.br
\fIcarte_b\fP dernière carte poser 
.RE
.PP
\fBRenvoie\fP
.RS 4
1 si le joueur peu jouer, 0 sinon\&. 
.RE
.PP

.SS "int can_play_cart (\fBcard_t\fP * carte_A, \fBcard_t\fP * carte_B)"
Vérifie si la carte peut être jouée\&. 
.PP
\fBParamètres\fP
.RS 4
\fIcarte_A\fP carte a comparer 
.br
\fIcarte_b\fP dernière carte poser 
.RE
.PP
\fBRenvoie\fP
.RS 4
1 si la carte peut etre jouer, 0 sinon\&. 
.RE
.PP

.SS "int getTour ()"

.PP
Renvoie la valeur des tours jouer\&. Recupere la variable global du numero tour\&. 
.PP
\fBRenvoie\fP
.RS 4
numero du tour 
.RE
.PP

.SS "void inverse ()"

.PP
Change de sens\&. Inverse la valeur de la varaiable global d'incémentation du tour\&. 
.SS "void next ()"

.PP
Passe au tour suivant\&. Increment la variable global comptant le numero du tour\&. 
.SS "int play (\fBplayer_t\fP * joueurs, \fBpile_t\fP * paquets, \fBpile_t\fP * pioches, int numt, int nbj, \fBcsv_t\fP * csv)"

.PP
Boucle principale du jeu\&. Fonction principlale du jeu Fait jouer un joueur et effectue tous les tests\&. 
.PP
\fBParamètres\fP
.RS 4
\fIjoueurs\fP vecteur contenent les joueurs\&. 
.br
\fIpaquets\fP pile sur laquel les joueurs posent leur carte\&. 
.br
\fIpioche\fP pile : la pioche 
.br
\fInumt\fP indice du joueur 
.br
\fInbj\fP nombre de joueur 
.br
\fIcsv\fP ensemble des messages a afficher 
.RE
.PP

.SS "void setTour (int n)"

.PP
Modifie la valeur de tour\&. Definie le numero du tour\&. 
.PP
\fBParamètres\fP
.RS 4
\fIn\fP nouvelle valeur du numero du tour\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour UNO à partir du code source\&.
